### PR TITLE
Homepage design

### PR DESCRIPTION
**Pull request by jessabean**
Fixes exercism/website#6

This PR does the following:
- Sets up file structure for stylesheets: dependencies, base, and modules
- Styles for the home page (right now, just the root/welcome page)
- Tested in latest versions of Chrome, Firefox, and Safari; IE9+ (maybe we should discuss browser/device support?)

Still to do:
- The Get Started button should link to a login action
- Links not working in footer because I am still not sure if Emblem.js will allow you to mix HTML tags and raw text. The source of much fist shaking today.
- Responsive design -- got started on this, realized we were missing a couple of breakpoints in the design, but this shouldn't be too hard to address. Will get a second PR going.
- Testing on mobile devices -- need to get a testing environment set up at home.
- Apply these styles/structure to the other public-facing pages. Those should go a bit quicker now that there is a baseline style.

Tasty screenshots -- the header section:

Tasty screenshots -- the features/try it section:

### CODE REVIEW

**Comment by kytrinyx** [comment]
I love this!

I changed the front-page text recently on the main site, trying to make it clearer that it's about the conversation.
Would you mind updating this to match?

https://github.com/exercism/exercism.io/blob/master/lib/app/views/site/index.haml#L13-L37

Before:
before
After:
after

**Comment by kytrinyx** [comment]
Oh, and the login stuff. I had a discussion with @mikepack about how to do this in #4 — I will add the necessary endpoints to the existing prototype API so that we can work against that.

**Comment by mikepack** [comment]
@jessabean this looks awesome! I'm going to merge now and allow @kytrinyx to update copy. Definitely a couple things to address, most of which you're already aware of.

From the designs, it looks like we are sharing the header with the exception of "Login with GitHub" vs "Logout". We can address this later, but I see that the Exercism logo is currently in the header. I'm wondering if we're looking at two different comps or if you took some liberties (which is fine by me).

**Comment by jessabean** [comment]
@mikepack You're right about the header...I had stubbed that alternate logo in as a placeholder because I was going to make a suggestion, and then completely forgot about it.

Should be super easy to update the design with suggestions above.

**Comment by kytrinyx** [comment]
Yay, I'll go make those text changes. Thank you :heart: :heart: :heart:

**Pull request merged**
